apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "spfa.fullname" . }}
  labels:
    {{- include "spfa.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "spfa.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ include "spfa.name" . }}-cron
              image: busybox:1.36
              command:
{{ toYaml .Values.cronjob.command | indent 16 }}
