apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spfa.fullname" . }}
  labels:
    app: spfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spfa
  template:
    metadata:
      labels:
        app: spfa
    spec:
      containers:
        - name: spfa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ include "spfa.fullname" . }}-config
            - secretRef:
                name: {{ include "spfa.fullname" . }}-secret
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
