{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spfa-cron
  labels:
    app: spfa-cron
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: spfa-cron
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: {{ toYaml .Values.cronjob.command | nindent 14 }}
{{- end }}
