{{- if and .Values.secret.enabled .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: spfa-secret
  labels:
    app: spfa
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
